version: '3.8'
networks:
  cluster_demo:
    driver: bridge
services:
  mysql:
    networks:
      - cluster_demo
    platform: linux/amd64
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cluster_demo
  userapi:
    networks:
      - cluster_demo
    hostname: userapi
    image: dhij.test/cluster-demo:latest
    command: "/bin/userapi"
    ports:
      - "8080:8080"
    depends_on:
      - mysql